[tox]
envlist =
    py313-pydantic2
;    py313-pydantic1
    py312-pydantic2
;    py312-pydantic1
    py311-pydantic2
    py311-pydantic1
    py310-pydantic2
    py310-pydantic1

;    py39-pydantic1
;    py39-pydantic2

[testenv]
allowlist_externals = *
;skip_install = true

deps =
    pytest
    pytest-asyncio
    httpx
    aiosqlite
    greenlet
;    pydantic1: pydantic>=1.10.13,<2.0.0
;    pydantic2: pydantic>=2.0.0,<3.0.0
commands =
    pytest

commands_pre=
    pip install poetry
    poetry lock --no-update
    poetry install --with dev -E pydantic-settings


[testenv:py39-pydantic1]
commands_pre=
    pip install "pydantic==1.10.13" --upgrade

basepython = python3.9



[testenv:py310-pydantic1]
basepython = /Users/nadir/.asdf/installs/python/3.10.15/bin/python
commands_pre=
    pip install "pydantic==1.10.13" --upgrade

[testenv:py311-pydantic1]
basepython = /Users/nadir/.asdf/installs/python/3.11.10/bin/python
commands_pre=
    pip install "pydantic==1.10.13" --upgrade

[testenv:py312-pydantic1]
basepython = /Users/nadir/.asdf/installs/python/3.12.4/bin/python
commands_pre=
    pip install "pydantic==1.10.13" --upgrade

[testenv:py313-pydantic1]
basepython = /Users/nadir/.asdf/installs/python/3.13.0/bin/python
commands_pre=
    pip install "pydantic==1.10.13" --upgrade

[testenv:py39-pydantic2]
basepython = python3.9
deps=
    pytest
    httpx
    pydantic-settings
    pytest-asyncio
    aiosqlite
    greenlet
commands_pre=
    pip install "pydantic>=2" --upgrade


[testenv:py310-pydantic2]
basepython = /Users/nadir/.asdf/installs/python/3.10.15/bin/python
commands_pre =
    pip install "pydantic>=2" --upgrade

deps=
    pytest
    pytest-asyncio
    httpx
    pydantic-settings
    aiosqlite
    greenlet

[testenv:py311-pydantic2]
basepython = /Users/nadir/.asdf/installs/python/3.11.10/bin/python
commands_pre =
    pip install "pydantic>=2" --upgrade

deps=
    pytest
    pytest-asyncio
    httpx
    pydantic-settings
    aiosqlite
    greenlet


[testenv:py312-pydantic2]
basepython = /Users/nadir/.asdf/installs/python/3.12.4/bin/python
commands_pre =
    pip install "pydantic>=2" --upgrade

deps=
    pytest
    pytest-asyncio
    httpx
    pydantic-settings
    aiosqlite
    greenlet

[testenv:py313-pydantic2]
basepython = /Users/nadir/.asdf/installs/python/3.13.0/bin/python
commands_pre =
    pip install "pydantic>=2" --upgrade

deps=
    pytest
    pytest-asyncio
    httpx
    pydantic-settings
    aiosqlite
    greenlet
