[tox]
requires = tox-uv>=1
envlist =
    py{310,311,312,313}-pydantic{1,2}

[testenv]
dependency_groups = dev
deps =
    -e {toxinidir}/../furiousapi-core
    pydantic1: pydantic>=1.10.13,<2.0.0
    pydantic2: pydantic>=2.0.0,<3.0.0
commands = pytest {posargs}
